language: node_js
node_js:
- '6'
- '7'
script:
  - cd tangle-explorer-web
  - npm install
  - npm run build
  - tar -cvzf dist.tar.gz dist
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: OnMpn6LNm/pzQvVvcGPOtqNOMCnK759rzGixled1OQt1E6VxGot3LreBNHSOf95xr+w3dzCDIK7tVPQgjIkKglVAhI1KG30aQiuA8oYsXAbnbmbzQLYetWU1GBDIYbSOWJHtbsBj0KwEHP28Ynjar1G9sERjSx9flPmFb1C6EizA+MogYpA6p2SeF5HIUvuAh8hhIG548upE5wrh4xbCk88gvJbus9hzzS6hFaIstocaLs5/u4ICNa5VzDoh3p3wyQJ2rX7L22/R4+eDxSzAzFhivSwPd5zlW1omqemil+SHaKUfBPMp7zGav9QglA1TJlgHLMmemcGrfHu0EgQiNRiFi7ehlcDVkA5c+/jb6dhUj1LWhJ0FItQ7mSJwZrbB89CMgrl+THVc+BYlYYV+Fv7osB1aTH/DtJMmqRuuumDeKkZR4TYPzNdqtpeY0acsusYaktSRnPuS9MOkkhdpm346zeckgs8tdc8rIhVmM+v1XgdOPpM7rCs5YAGMb2IIX0itVGmr6s+yDAodd+UNdwtrCyzhEUX9g0PRT3UoLihcFJfujQyFQ4l+LZDLo1zKNknZNzWCVgEjNFqkphbBcjtiPyO45rLJ83yQjPXbU1tE4CXmz+AtsWiJrrOq1Jja7cnvapyPNeyn+OJVnG79tY5rzBogpKc8Op4UHdFjbng=
  file: dist.tar.gz
  on:
    repo: peterwilli/IOTA-tangle-explorer
